# Generated by Django 3.1.7 on 2021-03-08 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('StudentNumber', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreateTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 9, 23, 44, 757446), null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('vids', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='ANS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, null=True)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('StudentNumber', models.CharField(max_length=100, null=True)),
                ('QuestionName', models.CharField(max_length=100)),
                ('Grade', models.IntegerField()),
                ('Sending_time', models.DateField(default=datetime.date.today)),
                ('file', models.FileField(upload_to='books/pdfs/')),
                ('WhichQuestion', models.ManyToManyField(to='polls.Question')),
            ],
        ),
    ]
