# Generated by Django 3.1.7 on 2021-03-08 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='due',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 9, 24, 2, 134204), null=True),
        ),
    ]
